program: run_sample.py
name: irn-sweep
project: irn-patch
method: bayes
metric:
  name: val_macro_precision
  goal: maximize
parameters:
  patch_size:
    value: 256
  cam_crop_size:
    value: 224
  cam_batch_size:
    value: 64
  cam_num_epoches:
    value: 5
  cam_learning_rate:
    min: 0.00001
    max: 0.1
  cam_weight_decay:
    value: 0.0001

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
  - "--voc12_root=VOCdevkit/VOC2012"
  - "--train_cam"
  - "--cam_batch_size=256"
    
